I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 34, in script
    P "That's kinda gay."
Exception: Sayer 'P' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 34, in script
    P "That's kinda gay."
  File "C:\Users\aat11\Desktop\renpy-7.0.0-sdk\renpy\ast.py", line 624, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\aat11\Desktop\renpy-7.0.0-sdk\renpy\ast.py", line 537, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'P' is not defined.

Windows-8-6.2.9200
Ren'Py 7.0.0.196
Multigay 1.0
Wed Aug 22 16:41:53 2018
